const AUTH_SIGNUP = 'AUTH_SIGNUP';
const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
const AUTH_LOGIN = 'AUTH_LOGIN';
const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
const AUTH_GET_USER = 'AUTH_GET_USER';
const AUTH_LOGOUT = 'AUTH_LOGOUT';

export {
  AUTH_SIGNUP,
  AUTH_SIGNUP_START,
  AUTH_SIGNUP_SUCCESS,
  AUTH_SIGNUP_FAIL,
  AUTH_LOGIN,
  AUTH_LOGIN_START,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL,
  AUTH_GET_USER,
  AUTH_LOGOUT,
};
