const AUTH_LOGIN_EXISTING_USER = 'LOGIN_EXISTING_USER';
const AUTH_LOGIN_EXISTING_USER_SUCCESS = 'AUTH_LOGIN_EXISTING_USER_SUCCESS';
const AUTH_LOGIN_EXISTING_USER_FAIL = 'AUTH_LOGIN_EXISTING_USER_FAIL';

const AUTH_SIGNUP = 'AUTH_SIGNUP';
const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

const AUTH_LOGIN = 'AUTH_LOGIN';
const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

export {
  AUTH_LOGIN_EXISTING_USER,
  AUTH_LOGIN_EXISTING_USER_SUCCESS,
  AUTH_LOGIN_EXISTING_USER_FAIL,
  AUTH_SIGNUP,
  AUTH_SIGNUP_START,
  AUTH_SIGNUP_SUCCESS,
  AUTH_SIGNUP_FAIL,
  AUTH_LOGIN,
  AUTH_LOGIN_START,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL,
  AUTH_LOGOUT,
  AUTH_LOGOUT_START,
  AUTH_LOGOUT_SUCCESS,
  AUTH_LOGOUT_FAIL,
  AUTH_CLEAR_ERROR,
};
