const CREATE_EXAM = 'CREATE_EXAM';
const CREATE_EXAM_START = 'CREATE_EXAM_START';
const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL';
const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';

const ADD_EXAM_QUESTION = 'ADD_EXAM_QUESTION';
const ADD_EXAM_QUESTION_START = 'ADD_EXAM_QUESTION_START';
const ADD_EXAM_QUESTION_FAIL = 'ADD_EXAM_QUESTION_FAIL';
const ADD_EXAM_QUESTION_SUCCESS = 'ADD_EXAM_QUESTION_SUCCESS';

const ADD_EXAM_STUDENT = 'ADD_EXAM_STUDENT';
const ADD_EXAM_STUDENT_START = 'ADD_EXAM_STUDENT_START';
const ADD_EXAM_STUDENT_FAIL = 'ADD_EXAM_STUDENT_FAIL';
const ADD_EXAM_STUDENT_SUCCESS = 'ADD_EXAM_STUDENT_SUCCESS';

export {
  CREATE_EXAM,
  CREATE_EXAM_START,
  CREATE_EXAM_FAIL,
  CREATE_EXAM_SUCCESS,
  ADD_EXAM_QUESTION,
  ADD_EXAM_QUESTION_START,
  ADD_EXAM_QUESTION_FAIL,
  ADD_EXAM_QUESTION_SUCCESS,
  ADD_EXAM_STUDENT,
  ADD_EXAM_STUDENT_START,
  ADD_EXAM_STUDENT_FAIL,
  ADD_EXAM_STUDENT_SUCCESS,
};
