const CREATE_EXAM_CHANGE_PART = 'CREATE_EXAM_CHANGE_PART';
const CREATE_EXAM_RESET = 'CREATE_EXAM_RESET';
const CREATE_EXAM_TITLE = 'CREATE_EXAM_TITLE';
const CREATE_EXAM_QUESTIONS = 'CREATE_EXAM_QUESTIONS';
const CREATE_EXAM_STUDENTS = 'CREATE_EXAM_STUDENTS';
const CREATE_EXAM = 'CREATE_EXAM';
const CREATE_EXAM_START = 'CREATE_EXAM_START';
const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL';
const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';

export {
  CREATE_EXAM_CHANGE_PART,
  CREATE_EXAM_RESET,
  CREATE_EXAM_TITLE,
  CREATE_EXAM_QUESTIONS,
  CREATE_EXAM_STUDENTS,
  CREATE_EXAM,
  CREATE_EXAM_START,
  CREATE_EXAM_FAIL,
  CREATE_EXAM_SUCCESS,
};
