const CREATE_EXAM_CHANGE_PART = 'CREATE_EXAM_CHANGE_PART';
const CREATE_EXAM_RESET = 'CREATE_EXAM_RESET';
const CREATE_EXAM_TITLE = 'CREATE_EXAM_TITLE';
const CREATE_EXAM_QUESTIONS = 'CREATE_EXAM_QUESTIONS';
const CREATE_EXAM_STUDENTS = 'CREATE_EXAM_STUDENTS';
const CREATE_EXAM = 'CREATE_EXAM';
const CREATE_EXAM_START = 'CREATE_EXAM_START';
const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL';
const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';

const GET_EXAM = 'GET_EXAM';
const GET_EXAM_START = 'GET_EXAM_START';
const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
const GET_EXAM_FAIL = 'GET_EXAM_FAIL';
const GET_USER_EXAMS = 'GET_USER_EXAMS';
const GET_USER_EXAMS_START = 'GET_USER_EXAMS_START';
const GET_USER_EXAMS_SUCCESS = 'GET_USER_EXAMS_SUCCESS';
const GET_USER_EXAMS_FAIL = 'GET_USER_EXAMS_FAIL';

export {
  CREATE_EXAM_CHANGE_PART,
  CREATE_EXAM_RESET,
  CREATE_EXAM_TITLE,
  CREATE_EXAM_QUESTIONS,
  CREATE_EXAM_STUDENTS,
  CREATE_EXAM,
  CREATE_EXAM_START,
  CREATE_EXAM_FAIL,
  CREATE_EXAM_SUCCESS,
  GET_EXAM,
  GET_EXAM_START,
  GET_EXAM_SUCCESS,
  GET_EXAM_FAIL,
  GET_USER_EXAMS,
  GET_USER_EXAMS_START,
  GET_USER_EXAMS_SUCCESS,
  GET_USER_EXAMS_FAIL,
};
