const CREATE_EXAM_CHANGE_PART = 'CREATE_EXAM_CHANGE_PART';
const CREATE_EXAM_RESET = 'CREATE_EXAM_RESET';
const CREATE_EXAM_TITLE = 'CREATE_EXAM_TITLE';
const CREATE_EXAM_QUESTIONS = 'CREATE_EXAM_QUESTIONS';
const CREATE_EXAM_STUDENTS = 'CREATE_EXAM_STUDENTS';
const CREATE_EXAM = 'CREATE_EXAM';
const CREATE_EXAM_START = 'CREATE_EXAM_START';
const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL';
const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';

const GET_EXAM = 'GET_EXAM';
const GET_EXAM_START = 'GET_EXAM_START';
const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
const GET_EXAM_FAIL = 'GET_EXAM_FAIL';
const GET_USER_EXAMS = 'GET_USER_EXAMS';
const GET_USER_EXAMS_START = 'GET_USER_EXAMS_START';
const GET_USER_EXAMS_SUCCESS = 'GET_USER_EXAMS_SUCCESS';
const GET_USER_EXAMS_FAIL = 'GET_USER_EXAMS_FAIL';

const DELETE_EXAM = 'DELETE_EXAM';
const DELETE_EXAM_START = 'DELETE_EXAM_START';
const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
const DELETE_EXAM_FAIL = 'DELETE_EXAM_FAIL';

const EDIT_EXAM_SELECT_EXAM = 'EDIT_EXAM_SELECT_EXAM';
const EDIT_EXAM_RESET = 'EDIT_EXAM_RESET';
const EDIT_EXAM_CHANGE_PART = 'EDIT_EXAM_CHANGE_PART';
const EDIT_EXAM_TITLE = 'EDIT_EXAM_TITLE';
const EDIT_EXAM_QUESTIONS = 'EDIT_EXAM_QUESTIONS';
const EDIT_EXAM_STUDENTS = 'EDIT_EXAM_STUDENTS';
const EDIT_EXAM = 'EDIT_EXAM';
const EDIT_EXAM_START = 'EDIT_EXAM_START';
const EDIT_EXAM_FAIL = 'EDIT_EXAM_FAIL';
const EDIT_EXAM_SUCCESS = 'EDIT_EXAM_SUCCESS';

export {
  CREATE_EXAM_CHANGE_PART,
  CREATE_EXAM_RESET,
  CREATE_EXAM_TITLE,
  CREATE_EXAM_QUESTIONS,
  CREATE_EXAM_STUDENTS,
  CREATE_EXAM,
  CREATE_EXAM_START,
  CREATE_EXAM_FAIL,
  CREATE_EXAM_SUCCESS,
  GET_EXAM,
  GET_EXAM_START,
  GET_EXAM_SUCCESS,
  GET_EXAM_FAIL,
  GET_USER_EXAMS,
  GET_USER_EXAMS_START,
  GET_USER_EXAMS_SUCCESS,
  GET_USER_EXAMS_FAIL,
  DELETE_EXAM,
  DELETE_EXAM_START,
  DELETE_EXAM_SUCCESS,
  DELETE_EXAM_FAIL,
  EDIT_EXAM_SELECT_EXAM,
  EDIT_EXAM_RESET,
  EDIT_EXAM_CHANGE_PART,
  EDIT_EXAM_TITLE,
  EDIT_EXAM_QUESTIONS,
  EDIT_EXAM_STUDENTS,
  EDIT_EXAM,
  EDIT_EXAM_START,
  EDIT_EXAM_FAIL,
  EDIT_EXAM_SUCCESS,
};
